/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package corrida;

public class App {
    
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Veiculo boeing = new Veiculo(new Motor());
        Veiculo jato = new Veiculo(new Motor());
        Veiculo supersonicos = new Veiculo(new Motor());
        Veiculo helice = new Veiculo(new Motor());
        System.out.println(boeing.voar());
        System.out.println(jato.voar());
        System.out.println(supersonicos.voar());
        System.out.println(helice.voar());
    }
}

